-d E:\Project\github\news_bot\TesterFPGA\src\FPGA_tester\impl\gwsynthesis\FPGA_tester.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\Project\github\news_bot\TesterFPGA\src\FPGA_tester\src\out.cst
-cfg E:\Project\github\news_bot\TesterFPGA\src\FPGA_tester\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
