-d F:\github\TesterFPGA\FPGA_tester\impl\gwsynthesis\FPGA_tester.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst F:\github\TesterFPGA\FPGA_tester\src\out.cst
-cfg F:\github\TesterFPGA\FPGA_tester\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
